version: 2 

seeds: 
  - name: product
    config: 
      schema: production
      column_types: 
        productid: integer
        name: string
        safetystocklevel: INT64
        finishedgoodsflag: boolean 
        class: string
        makeflag: boolean
        productnumber: string
        reorderpoint: INT64
        modifieddate: timestamp
        rowguid: string
        productmodelid: integer
        weightunitmeasurecode: string
        standardcost: numeric
        productsubcategoryid: integer
        listprice: numeric
        daystomanufacture: integer
        productline: string
        color: string
        sellstartdate: timestamp
        weight: numeric
